# Generated by Django 2.0 on 2019-04-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Douban_top',
            fields=[
                ('rankey', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('alias', models.TextField()),
                ('director', models.TextField()),
                ('showYear', models.TextField()),
                ('makeCountry', models.TextField()),
                ('movieType', models.TextField()),
                ('movieScore', models.TextField()),
                ('scoreNum', models.TextField()),
                ('shortFilm', models.TextField()),
            ],
        ),
    ]
