# Generated by Django 2.0 on 2019-04-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tianqi_sun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('weather', models.TextField()),
                ('wind', models.TextField()),
                ('max', models.TextField()),
                ('min', models.TextField()),
            ],
        ),
    ]
