# Generated by Django 2.0 on 2019-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tianqi_sun'),
    ]

    operations = [
        migrations.CreateModel(
            name='jingdong_test',
            fields=[
                ('dong_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop', models.TextField()),
                ('comment', models.TextField()),
                ('shop_type', models.TextField()),
                ('price', models.TextField()),
                ('dong_name', models.TextField()),
            ],
        ),
    ]
